=== metno/metamod/common/schema/MM2.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0" encoding="iso8859-1"?>
    <?xml-stylesheet href="MM2.xsl" type="text/xsl"?>
    <MM2
       xmlns="http://www.met.no/schema/metamod/MM2"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
      <metadata name="test">value</metadata>
    </MM2>

-->
<schema
  xmlns='http://www.w3.org/2001/XMLSchema'
  targetNamespace='http://www.met.no/schema/metamod/MM2'
  xmlns:t='http://www.met.no/schema/metamod/MM2'>
      
    <complexType name='Mm2'>
        <sequence>
            <element ref='t:metadata' minOccurs='0' maxOccurs='unbounded'/>
        </sequence>
    </complexType>
    <complexType name='MetaData'>
        <simpleContent>
            <extension base="string">
                <attribute name='name' type='string' use='required' />
            </extension>
        </simpleContent>
    </complexType>

    <element name='MM2' type='t:Mm2' />
    <element name='metadata' type='t:MetaData' />
</schema>

=== metno/metamod/test/xmlinput/conc.xml
<?xml version="1.0" encoding="iso8859-1"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:ns1="http://www.w3.org/2001/XMLSchema-instance" ns1:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
  <metadata name="datacollection_period_from">2006-05-01</metadata>
  <metadata name="datacollection_period_to">2099-01-01</metadata>
  <metadata name="bounding_box">179.926,31.0883,-180,89.9347</metadata>
  <metadata name="dataref">http://mersea.met.no/cgi-bin/nph-dods/data/seaice/conc/</metadata>
  <metadata name="field_type">daily</metadata>
  <metadata name="Conventions">CF-1.0</metadata>
  <metadata name="area">Northern Hemisphere</metadata>
  <metadata name="contact">osisaf-manager@met.no</metadata>
  <metadata name="operational_status">Operational</metadata>
  <metadata name="product_version">2.1</metadata>
  <metadata name="references">OSI SAF Sea Ice Product Manual, Andersen S., Breivik L.A., Eastwood S., Godøy Ø., Lind M., Porcires M., Schyberg H., v3.2, October 2005. http://www.osi-saf.org</metadata>
  <metadata name="spatial_resolution">10.0km</metadata>
  <metadata name="software_version">3.2</metadata>
  <metadata name="title">Total Sea Ice Concentration from EUMETSAT OSI SAF</metadata>
  <metadata name="institution">met.no Norwegian Meteorological Institute</metadata>
  <metadata name="activity_type">Space borne instrument</metadata>
  <metadata name="variable">ice_concentration</metadata>
  <metadata name="variable">Cryosphere &gt; Sea Ice &gt; Sea Ice Concentration &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Sea Ice &gt; Sea Ice Concentration &gt; HIDDEN</metadata>
</MM2>

=== metno/metamod/test/xmlinput/met.no_1.xml
<?xml version="1.0" encoding="iso8859-1"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:ns1="http://www.w3.org/2001/XMLSchema-instance" ns1:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
  <metadata name="datacollection_period_from">2006-09-01</metadata>
  <metadata name="datacollection_period_to">2008-09-01</metadata>
  <metadata name="institution">met.no Norwegian Meteorological Institute</metadata>
  <metadata name="contact">c.mauritzen@met.no</metadata>
  <metadata name="dataref">met.no-1 (planned activity)</metadata>
  <metadata name="activity_type">Moored instrument</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Ocean Currents &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Water Masses &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Heat Budget &gt; Advection &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Temperature &gt; Potential Temperature &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Salinity/Density &gt; Salinity &gt; HIDDEN</metadata>
  <metadata name="area">Central Arctic</metadata>
  <metadata name="abstract">
Bottom-anchored profiler. Will be deployed by Kapitan Dranitsyn September 2006 at 32W on the continental
slope
   </metadata>
</MM2>

=== metno/metamod/test/xmlinput/svinoy-mooring/svinoy-mooring_S1-300m.xml
<?xml version="1.0" encoding="utf-8"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
<metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_pressure</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_temperature</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_speed</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">direction_of_sea_water_velocity</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">Oceans &gt; Ocean Circulation &gt; Ocean Currents Oceans &gt; Ocean Temperature &gt; Water Temperature Oceans &gt; Salinity/Density &gt; Salinity Oceans &gt; Ocean Pressure &gt; Water Pressure &gt; HIDDEN</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">depth</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_salinity</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="area">Nordic Seas</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="contact">Kjell.Orvik@gfi.uib.no</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="topiccategory">oceans</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="PI_name">Kjell Arild Orvik</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="keywords">ocean current temperature salinity pressure</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="datacollection_period_from">2005-12-01</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="activity_type">Moored instrument</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="project_name">DAMOCLES</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="Conventions">CF-1.0</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="Platform_name">Svinøy S1 mooring</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="history">2008-11-26 Created</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="distribution_statement">Restricted to Damocles</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="datacollection_period_to">2008-10-07</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="abstract">Mooring observing current, temperature, salinity and pressure. The mooring is 
named S1 in the Svinøy section and positioned at 62o 49.33 N, 4o 17.41 E. The 
depth is 500m and the dataset contains hourly records (raw data) from 100m and 
300m. Time is specified in UTC. </metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="title">Svinøy S1 mooring</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="bounding_box">4.2901667,62.8221667,4.2901667,62.8221667</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="institution">UiB University of Bergen</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="product_name">Svinøy S1 mooring 100m and 300m</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="dataref">http://thredds.met.no/thredds/catalog/data/UiB/svinoy-mooring/catalog.html?dataset=UiB/svinoy-mooring/svinoy-mooring_S1-300m.nc</metadata></MM2>

=== metno/metamod/test/xmlinput/ice/ice_conc_nh_200910191200_CF.xml
<?xml version="1.0" encoding="utf-8"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
<metadata name="variable">Geographic Region &gt; Northern Hemipshere &gt; HIDDEN</metadata><metadata name="variable">Cryosphere &gt; Sea Ice &gt; Sea Ice Concentration &gt; HIDDEN</metadata><metadata name="variable">sea_ice_concentration</metadata><metadata name="variable">Ocean &gt; Sea Ice &gt; Sea Ice Concentration &gt; HIDDEN</metadata><metadata name="variable">Vertical Location &gt; Sea Surface &gt; HIDDEN</metadata><metadata name="variable">EUMETSAT/OSISAF &gt; Satellite Application Facility on Ocean and Sea Ice, European Organisation for the Exploitation of Meteorological Satellites &gt; HIDDEN</metadata><metadata name="area">Northern Hemisphere</metadata><metadata name="contact">osisaf-manager@met.no</metadata><metadata name="topiccategory">climatologyMeteorologyAtmosphere</metadata><metadata name="topiccategory">oceans</metadata><metadata name="PI_name">Rasmus Tonboe</metadata><metadata name="product_version">2.2</metadata><metadata name="keywords">Climate</metadata><metadata name="keywords">Sea Ice</metadata><metadata name="keywords">Oceanography</metadata><metadata name="keywords">Meteorology</metadata><metadata name="keywords">Sea Ice Concentration</metadata><metadata name="keywords">Remote Sensing</metadata><metadata name="references">OSI SAF Sea Ice Product Manual, Eastwood S. (editor), v3.6, September 2009
http://saf.met.no
http://www.osi-saf.org</metadata><metadata name="datacollection_period_from">2009-10-19</metadata><metadata name="activity_type">Space borne instrument</metadata><metadata name="project_name">EUMETSAT OSI SAF</metadata><metadata name="Conventions">CF-1.3</metadata><metadata name="history">2009-10-20 creation</metadata><metadata name="distribution_statement">Free</metadata><metadata name="software_version">4.0</metadata><metadata name="datacollection_period_to">2009-10-19</metadata><metadata name="abstract">The daily analysis of sea ice concentration are obtained from
operation 
satellite images of the polar regions. It is based
on atmospherically 
corretected signal and an optimal sea ice
concentration algorithm. This product 
is available for free
from the EUMETSAT Ocean and Sea Ice Satellite 
Application
Facility (OSI SAF). </metadata><metadata name="title">OSI SAF Daily Sea Ice Concentration Analysis</metadata><metadata name="bounding_box">180,31.019287109375,-180,90</metadata><metadata name="institution">EUMETSAT OSI SAF</metadata><metadata name="product_name">osi_saf_ice_conc</metadata><metadata name="dataref">http://damocles.met.no:8080/thredds/catalog/data/TUN/ice/catalog.html?dataset=TUN/ice/ice_conc_nh_200910191200_CF.nc</metadata></MM2>

=== metno/metamod/test/xmlinput/NPI_1.xml
<?xml version="1.0" encoding="iso8859-1"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:ns1="http://www.w3.org/2001/XMLSchema-instance" ns1:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
  <metadata name="institution">NPI Norwegian Polar Institute</metadata>
  <metadata name="contact">edmond.hansen@npolar.no</metadata>
  <metadata name="dataref">NPI-1 (planned activity)</metadata>
  <metadata name="activity_type">Cruise</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Water Masses &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Temperature &gt; Ocean Mixed Layer &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Temperature &gt; Potential Temperature &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Temperature &gt; Water Temperature &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Salinity/Density &gt; Density &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Salinity/Density &gt; Salinity &gt; HIDDEN</metadata>
  <metadata name="area">Fram Strait</metadata>
  <metadata name="abstract">
Annual cruises with RV Lance
   </metadata>
</MM2>

=== metno/metamod/test/xmlinput/metno_arctic20.200609.xml
<?xml version="1.0" encoding="iso8859-1"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:ns1="http://www.w3.org/2001/XMLSchema-instance" ns1:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
  <metadata name="datacollection_period_from">2006-09-01</metadata>
  <metadata name="datacollection_period_to">2006-09-30</metadata>
  <metadata name="bounding_box">179.956,45.2402,-179.995,89.9033</metadata>
  <metadata name="dataref">http://damocles.met.no:8080/thredds/dodsC/data/met.no/metno/metno_arctic20.200609.nc</metadata>
  <metadata name="topiccategory">oceans</metadata>
  <metadata name="area">Arctic Ocean</metadata>
  <metadata name="area">Nordic Seas</metadata>
  <metadata name="forecast_range">0029-days forecast</metadata>
  <metadata name="contact">jens.debernard@met.no</metadata>
  <metadata name="references">http://met.no/english/r_and_d_activities/method/num_mod/mi_pom.html, http://met.no/english/r_and_d_activities/method/num_mod/mi_im.html</metadata>
  <metadata name="operational_status">Operational</metadata>
  <metadata name="PI_name">Jens Debernard</metadata>
  <metadata name="product_version">1.0</metadata>
  <metadata name="forecast_type">nowcast</metadata>
  <metadata name="keywords">forecast</metadata>
  <metadata name="keywords">sea</metadata>
  <metadata name="keywords">ice</metadata>
  <metadata name="keywords">asimillation</metadata>
  <metadata name="Conventions">CF-1.0</metadata>
  <metadata name="history">2006-11-29 creation</metadata>
  <metadata name="grid_projection">polar_stereographic</metadata>
  <metadata name="distribution_statement">Free</metadata>
  <metadata name="product_name">coupled MI-POM, MI-IM model</metadata>
  <metadata name="software_version">MIPOM v. 23, MI-IM v. 3</metadata>
  <metadata name="abstract">
This data set contains ice concentration (fraction of ice), and sea surface 
temperature analysis from the met.no operational coupled ice-ocean model 
Arctic-20. Each file contains one month of daily analysis valid at 00 GMT. The 
quality of this data set will vary due to model upgrades, and should therefore 
in the long term, improve with time. New model-versions are tested 
semi-operationally before they are included in this data set. 
   </metadata>
  <metadata name="title">met.no DAMOCLES sea ice operational ice concentration and sst</metadata>
  <metadata name="institution">met.no Norwegian Meteorological Institute</metadata>
  <metadata name="variable">sea_ice_area_fraction</metadata>
  <metadata name="variable">sea_water_temperature</metadata>
</MM2>

=== metno/metamod/test/xmlinput/ark22.xml
<?xml version="1.0" encoding="iso8859-1"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:ns1="http://www.w3.org/2001/XMLSchema-instance" ns1:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
  <metadata name="datacollection_period_from">2007-07-29</metadata>
  <metadata name="datacollection_period_to">2007-10-06</metadata>
  <metadata name="bounding_box">-135.,72.,26.,89.</metadata>
  <metadata name="dataref">http://thredds.met.no/thredds/catalog/data/AWI/ark22/</metadata>
  <metadata name="area">Arctic Ocean</metadata>
  <metadata name="contact">Andreas.Wisotzki@awi.de</metadata>
  <metadata name="topiccategory">oceans</metadata>
  <metadata name="PI_name">Andreas Wisotzki</metadata>
  <metadata name="Platform_name">R/V Polarstern</metadata>
  <metadata name="distribution_statement">Data restriction: for DAMOCLES partners only</metadata>
  <metadata name="software_version">Seabird: SeasaveWin32, Version 5.37d, SBE Data Processing, Version 5.37e</metadata>
  <metadata name="institution">AWI Alfred Wegener Institute for Polar and Marine Research</metadata>
  <metadata name="product_name">CTD temperature, salinity, dissolved oxygen and light transmission at 191 stations in the Arctic Ocean</metadata>
  <metadata name="abstract">
CTD temperature, salinity, dissolved oxygen and light transmission at 191 stations in the Arctic Ocean
   </metadata>
  <metadata name="variable">sea_water_dissolved_oxygen</metadata>
  <metadata name="variable">sea_water_temperature</metadata>
  <metadata name="variable">sea_water_light_transmission</metadata>
  <metadata name="variable">sea_water_salinity</metadata>
</MM2>

=== metno/metamod/test/xmlinput/awiem.xml
<?xml version="1.0" encoding="iso8859-1"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:ns1="http://www.w3.org/2001/XMLSchema-instance" ns1:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
  <metadata name="datacollection_period_from">2007-04-16</metadata>
  <metadata name="datacollection_period_to">2007-04-16</metadata>
  <metadata name="bounding_box">34.54,87.06,-57.88,89.61</metadata>
  <metadata name="variable">sea_ice_thickness</metadata>
  <metadata name="variable">altitude</metadata>
  <metadata name="variable">Cryosphere &gt; Sea Ice &gt; Ice Depth/Thickness &gt; HIDDEN</metadata>
  <metadata name="area">Arctic Ocean</metadata>
  <metadata name="contact">Christian.Haas@ualberta.ca</metadata>
  <metadata name="topiccategory">oceans</metadata>
  <metadata name="PI_name">Christian Haas</metadata>
  <metadata name="keywords">sea ice thickness</metadata>
  <metadata name="activity_type">Aircraft</metadata>
  <metadata name="project_name">Damocles,TotalPoleAirship</metadata>
  <metadata name="Conventions">CF-1.0</metadata>
  <metadata name="history">2007-04-16 creation</metadata>
  <metadata name="distribution_statement">Free</metadata>
  <metadata name="abstract">
A 350 km long HEM profile of ice thickness has been obtained between the North 
Pole and 87N, 60W, in April 2007 as part of the Damocles Tara activities 
   </metadata>
  <metadata name="title">Helicopter EM ice thickness profile</metadata>
  <metadata name="institution">AWI Alfred Wegener Institute for Polar and Marine Research</metadata>
  <metadata name="product_name">HEM ice thickness</metadata>
  <metadata name="dataref">http://thredds.met.no/thredds/catalog/data/AWI/awiem/</metadata>
</MM2>
