=== metno/metamod/common/schema/MM2.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0" encoding="iso8859-1"?>
    <?xml-stylesheet href="MM2.xsl" type="text/xsl"?>
    <MM2
       xmlns="http://www.met.no/schema/metamod/MM2"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
      <metadata name="test">value</metadata>
    </MM2>

-->
<schema
  xmlns='http://www.w3.org/2001/XMLSchema'
  targetNamespace='http://www.met.no/schema/metamod/MM2'
  xmlns:t='http://www.met.no/schema/metamod/MM2'>
      
    <complexType name='Mm2'>
        <sequence>
            <element ref='t:metadata' minOccurs='0' maxOccurs='unbounded'/>
        </sequence>
    </complexType>
    <complexType name='MetaData'>
        <simpleContent>
            <extension base="string">
                <attribute name='name' type='string' use='required' />
            </extension>
        </simpleContent>
    </complexType>

    <element name='MM2' type='t:Mm2' />
    <element name='metadata' type='t:MetaData' />
</schema>

=== metno/metamod/test/xmlinput/AWI_1.xml
<?xml version="1.0" encoding="iso8859-1"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:ns1="http://www.w3.org/2001/XMLSchema-instance" ns1:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
  <metadata name="datacollection_period_from">2005-07-01</metadata>
  <metadata name="datacollection_period_to">2009-09-01</metadata>
  <metadata name="institution">AWI Alfred Wegener Institute for Polar and Marine Research</metadata>
  <metadata name="contact">abeszczynska@awi-bremerhaven.de</metadata>
  <metadata name="dataref">AWI-1 (planned activity)</metadata>
  <metadata name="activity_type">Cruise</metadata>
  <metadata name="variable">Oceans &gt; Ocean Optics &gt; Attenuation/Transmission &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Pressure &gt; Water Pressure &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Temperature &gt; Potential Temperature &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Salinity/Density &gt; Conductivity &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Salinity/Density &gt; Potential Density &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Salinity/Density &gt; Salinity &gt; HIDDEN</metadata>
  <metadata name="area">Fram Strait</metadata>
  <metadata name="abstract">
CTD section across Fram Strait at 78deg50min N (along the moored array) performed on annual basis in
summer/autumn
   </metadata>
</MM2>

=== metno/metamod/test/xmlinput/itp17/itp17_itp17grd0229.xml
<?xml version="1.0" encoding="utf-8"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
<metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_pressure</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">Oceans &gt; Ocean Temperature &gt; Water Temperature &gt; HIDDEN</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">Oceans &gt; Salinity/Density &gt; Salinity &gt; HIDDEN</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_electrical_conductivity</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">Oceans &gt; Ocean Pressure &gt; Water Pressure &gt; HIDDEN</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_salinity</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="area">Arctic Ocean</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="contact">itp@whoi.edu</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="topiccategory">oceans</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="PI_name">Not available</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="keywords">pressure temperature salinity</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="datacollection_period_from">2007-10-21</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="activity_type">Float</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="project_name">Damocles</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="Conventions">CF-1.0</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="Platform_name">ITP 17</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="history">2009-03-13 creation</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="distribution_statement">Free</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="datacollection_period_to">2007-10-22</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="abstract">The Ice-Tethered Profiler data were collected and made available by the 
Ice-Tethered Profiler Program based at the Woods Hole Oceanographic Institution 
(http://www.whoi.edu/itp). ITP data are similar to CTD data, but are collected 
from buoys frozen in the sea ice. </metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="title">ITP 17 Profile</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="bounding_box">84.4166,87.4094,84.4166,87.4094</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="institution">Woods Hole Oceanographic Institute</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="product_name">ITP profile</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="dataref">http://thredds.met.no/thredds/catalog/data/met.no/itp17/catalog.html?dataset=met.no/itp17/itp17_itp17grd0229.nc</metadata></MM2>

=== metno/metamod/test/xmlinput/FSmoorings-2006-2007/FSmoorings-2006-2007_F6-10_2638m.xml
<?xml version="1.0" encoding="utf-8"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
<metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_temperature</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_pressure</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_speed</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">direction_of_sea_water_velocity</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">depth</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">eastward_sea_water_velocity</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_salinity</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">northward_sea_water_velocity</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="area">Fram Strait</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="contact">Agnieszka.Beszczynska-Moeller@awi.de</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="topiccategory">oceans</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="PI_name">Agnieszka Beszczynska-Moeller</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="keywords">moorings Fram Strait current meters</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="datacollection_period_from">2006-08-28</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="activity_type">Moored instrument</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="project_name">DAMOCLES IP</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="Conventions">CF-1.0</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="history">2009-01-21 creation</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="distribution_statement">Restricted to Damocles</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="datacollection_period_to">2007-09-11</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="abstract">Array of 12 deep moorings across Fram Strait at 78deg50min N maintained by AWI </metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="title">Fram Strat moored array data</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="bounding_box">5.02233333333333,78.8305,5.02233333333333,78.8305</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="product_name">Data from moored instrument</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="dataref">http://thredds.met.no/thredds/catalog/data/AWI/FSmoorings-2006-2007/catalog.html?dataset=AWI/FSmoorings-2006-2007/FSmoorings-2006-2007_F6-10_2638m.nc</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="institution">Alfred Wegener Institute for Polar and Marine Research, Bremerhaven, Germany</metadata></MM2>

=== metno/metamod/test/xmlinput/GFI_S1M10801.xml
<?xml version="1.0" encoding="iso8859-1"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:ns1="http://www.w3.org/2001/XMLSchema-instance" ns1:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
  <metadata name="datacollection_period_from">2006-10-02</metadata>
  <metadata name="datacollection_period_to">2007-03-21</metadata>
  <metadata name="bounding_box">4.29,62.8333333333,4.29,62.8333333333</metadata>
  <metadata name="dataref">http://thredds.met.no/thredds/dodsC/data/UiB/GFI/GFI_S1M10801.nc</metadata>
  <metadata name="topiccategory">oceans</metadata>
  <metadata name="contact">orvik@gfi.uib.no</metadata>
  <metadata name="PI_name">Kjell Arild Orvik</metadata>
  <metadata name="keywords">oceanography velocity salinity temperature pressure</metadata>
  <metadata name="references">http://www.gfi.uib.no/</metadata>
  <metadata name="Platform_name">GFI Rig S1</metadata>
  <metadata name="Conventions">CF-1.0</metadata>
  <metadata name="history">2007-05-11 Created</metadata>
  <metadata name="distribution_statement">Free</metadata>
  <metadata name="product_name">Mooring data</metadata>
  <metadata name="area">Norwegian Sea</metadata>
  <metadata name="abstract">
Moored rig at Svinøy observing current and some other parameters 
   </metadata>
  <metadata name="title">Svinøy mooring S1</metadata>
  <metadata name="institution">UiB University of Bergen</metadata>
  <metadata name="variable">direction_of_sea_water_velocity</metadata>
  <metadata name="variable">sea_water_speed</metadata>
  <metadata name="variable">eastward_sea_water_velocity</metadata>
  <metadata name="variable">northward_sea_water_velocity</metadata>
</MM2>

=== metno/metamod/test/xmlinput/oceania/oceania_ctd_AR07_051.xml
<?xml version="1.0" encoding="utf-8"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
<metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_pressure</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_temperature</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_electrical_conductivity</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_salinity</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="area">Barents Sea</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="area">Greenland Sea</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="contact">ilona_g@iopan.gda.pl</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="topiccategory">oceans</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="PI_name">Ilona Goszczko</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="product_version">1.0</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="operational_status">operational</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="keywords">Oceanography Pressure Temperature Coductivity Salinity</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="references">http://seabird.com</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="datacollection_period_from">2007-06-19</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="activity_type">Cruise</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="project_name">Damocles</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="project_name">AREX 2007</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="history">2007-07-22 creation</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="distribution_statement">Restricted to Damocles</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="quality_index">1</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="software_version">CTD Seabird SBE911plus, Seasave Win32 V 7.12</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="datacollection_period_to">2007-07-22</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="title">IO PAS CTD data file</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="abstract">IO PAS CTD data file from Arctic Cruise with R/V Oceania performed in summer 
2007 </metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="bounding_box">20.004,70.5,0.044,79.831</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="institution">IOPAN Instytut Oceanologii, Polska Akademia Nauk</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="product_name">oceania_ctd_ar07</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="dataref">http://thredds.met.no/thredds/catalog/data/IOPAS/oceania/catalog.html?dataset=IOPAS/oceania/oceania_ctd_AR07_051.nc</metadata></MM2>

=== metno/metamod/test/xmlinput/ocCTDar06/ocCTDar06_145.xml
<?xml version="1.0" encoding="utf-8"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
<metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_temperature</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_pressure</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_sigma_theta</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_electrical_conductivity</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_potential_temperature</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_salinity</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="area">Greenland Sea</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="contact">ocl@iopan.gda.pl</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="topiccategory">oceans</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="PI_name">Ocean Circulation Laboratory</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="keywords">Salinity/Density</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="keywords">Ocean Temperature</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="keywords">Greenland Sea</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="Conventions">CF1.0</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="Platform_name">R/V Oceania</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="distribution_statement">Data restrictions: for DAMOCLES partners only</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="abstract">IO PAS CTD data file from Arctic Cruise with R/V Oceania performed in summer 
2006 </metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="title">IO PAS CTD data file</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="product_name">oceania_ctd_ar06_145.nc</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="dataref">http://thredds.met.no/thredds/catalog/data/IOPAS/ocCTDar06/catalog.html?dataset=IOPAS/ocCTDar06/ocCTDar06_145.nc</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="institution">Institute of Oceanology, Polish Academy of Sciences</metadata></MM2>

=== metno/metamod/test/xmlinput/StorfjordADCP/StorfjordADCP_2006.xml
<?xml version="1.0" encoding="utf-8"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
<metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">Oceans, Ocean Circulation, Ocean Currents &gt; HIDDEN</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="area">Barents Sea</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="contact">ilker.fer@gfi.uib.no</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="PI_name">Ilker Fer</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="keywords">ADCP</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="keywords">Storfjorden</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="keywords">current</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="keywords">overflow</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="keywords">Microcat</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="activity_type">Moored instrument</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="project_name">DAMOCLES</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="Conventions">CF-1.0</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="Platform_name">Bottom mounted frame</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="distribution_statement">free</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="abstract">Under the Developing Arctic Modeling and Observing Capabilities for Long-term 
Environmental Studies (DAMOCLES) project, an acoustic Doppler current profiler 
(ADCP) and a Microcat were deployed at the sill separating the Storfjorden in 
Svalbard Archipelago and Storfjordrenna north of Storfjordbanken on the Barents 
Sea shelf. Storfjorden, through its polynya activity, produces highly saline 
water near the freezing temperature which fills the fjord to the sill level (115 
m) and initiates a gravity driven overflow. A self-contained 307.2 KHz broadband 
Workhorse, Sentinel, RD Instruments ADCP and a Sea-Bird SBE37SM Microcat (S/N 
4011), temperature-conductivity-pressure recording unit was deployed at 76deg 
58.08min N, 19deg 14.95min E at the 111 m isobath on 12 december 2005. The 
instruments were recovered on 9 August 2006. The instruments are installed in an 
aluminum trawl-proof frame, attached to a concrete block of 2.5x2.5x0.37 m 
dimensions. The ADCP sampled at 4-m depth cell size, averaging data (33 pings 
per ensemble) at 10 min intervals. The first cell was centered at about 6 meter 
above seafloor. The Microcat sampled at 10min intervals. This dataset consists 
of hourly averaged vertical profiles of current velocities as well as 
ADCP-temperature and Microcat-temperature/salinity/pressure at the instrument 
depth. </metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="title">Acoustic Doppler Current Profiler data from the Storfjorden Sill, 2005/2006</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="product_name">Horizontal velocity and temperature at Storfjorden Sill</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="dataref">http://thredds.met.no/thredds/catalog/data/UiB/StorfjordADCP/catalog.html?dataset=UiB/StorfjordADCP/StorfjordADCP_2006.nc</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="institution">UiB University of Bergen</metadata></MM2>

=== metno/metamod/test/xmlinput/icedriftC4.xml
<?xml version="1.0" encoding="iso8859-1"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:ns1="http://www.w3.org/2001/XMLSchema-instance" ns1:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
  <metadata name="datacollection_period_from">2005-05-10</metadata>
  <metadata name="datacollection_period_to">2006-02-10</metadata>
  <metadata name="bounding_box">179.635,56.0234,-178.51,90</metadata>
  <metadata name="dataref">http://thredds.met.no/thredds/catalog/data/DMI/icedriftC4/</metadata>
  <metadata name="area">Arctic Ocean</metadata>
  <metadata name="contact">gd@dmi.dk</metadata>
  <metadata name="topiccategory">oceans</metadata>
  <metadata name="PI_name">Gorm Dybkjaer</metadata>
  <metadata name="keywords">Ice drift</metadata>
  <metadata name="keywords">Arctic</metadata>
  <metadata name="keywords">IR</metadata>
  <metadata name="keywords">VIS</metadata>
  <metadata name="keywords">AVHRR</metadata>
  <metadata name="keywords">MCC</metadata>
  <metadata name="Platform_name">AVHRR</metadata>
  <metadata name="activity_type">Space borne instrument</metadata>
  <metadata name="project_name">DAMOCLES</metadata>
  <metadata name="Conventions">CF-1.0</metadata>
  <metadata name="history">2007-10-25 creation</metadata>
  <metadata name="distribution_statement">Free</metadata>
  <metadata name="abstract">
A 9 month ice drift data set based on VIS and IR data 
   </metadata>
  <metadata name="title">Ice drift in Greenland seas</metadata>
  <metadata name="product_name">Ice drift</metadata>
  <metadata name="institution">DMI Danish Meteorological Institute</metadata>
  <metadata name="variable">Cryosphere &gt; Sea Ice &gt; Sea Ice Motion &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Sea Ice &gt; Sea Ice Motion &gt; HIDDEN</metadata>
  <metadata name="variable">Ice displacement</metadata>
</MM2>
