=== metno/metamod/common/schema/MM2.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0" encoding="iso8859-1"?>
    <?xml-stylesheet href="MM2.xsl" type="text/xsl"?>
    <MM2
       xmlns="http://www.met.no/schema/metamod/MM2"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
      <metadata name="test">value</metadata>
    </MM2>

-->
<schema
  xmlns='http://www.w3.org/2001/XMLSchema'
  targetNamespace='http://www.met.no/schema/metamod/MM2'
  xmlns:t='http://www.met.no/schema/metamod/MM2'>
      
    <complexType name='Mm2'>
        <sequence>
            <element ref='t:metadata' minOccurs='0' maxOccurs='unbounded'/>
        </sequence>
    </complexType>
    <complexType name='MetaData'>
        <simpleContent>
            <extension base="string">
                <attribute name='name' type='string' use='required' />
            </extension>
        </simpleContent>
    </complexType>

    <element name='MM2' type='t:Mm2' />
    <element name='metadata' type='t:MetaData' />
</schema>

=== metno/metamod/test/xmlinput/FIMR_2.xml
<?xml version="1.0" encoding="iso8859-1"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:ns1="http://www.w3.org/2001/XMLSchema-instance" ns1:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
  <metadata name="datacollection_period_from">2006-04-01</metadata>
  <metadata name="datacollection_period_to">2009-11-30</metadata>
  <metadata name="institution">FIMR Finnish Institute of Marine Research</metadata>
  <metadata name="contact">rudels@fimr.fi</metadata>
  <metadata name="dataref">FIMR-2 (planned activity)</metadata>
  <metadata name="activity_type">Cruise</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Advection &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Convection &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Diffusion &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Eddies &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Fresh Water Flux &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Fronts &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Gyres &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Ocean Currents &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Ocean Mixed Layer &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Thermohaline Circulation &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Turbulence &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Upwelling/Downwelling &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Vorticity &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Water Masses &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Wind-driven Circulation &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Heat Budget &gt; Advection &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Heat Budget &gt; Convection &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Heat Budget &gt; Diffusion &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Heat Budget &gt; Evaporation &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Heat Budget &gt; Heat Flux &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Temperature &gt; Ocean Mixed Layer &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Temperature &gt; Thermocline &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Salinity/Density &gt; Halocline &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Salinity/Density &gt; Potential Density &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Salinity/Density &gt; Pycnocline &gt; HIDDEN</metadata>
  <metadata name="variable">Cryosphere &gt; Sea Ice &gt; Polynyas &gt; HIDDEN</metadata>
  <metadata name="area">Greenland Sea</metadata>
  <metadata name="area">Iceland Sea</metadata>
  <metadata name="area">Norwegian Sea</metadata>
  <metadata name="area">Fram Strait</metadata>
  <metadata name="area">Denmark Strait</metadata>
  <metadata name="area">Central Arctic</metadata>
  <metadata name="abstract">
Aranda, Oden
   </metadata>
</MM2>

=== metno/metamod/test/xmlinput/UGOT-data.xml
<?xml version="1.0" encoding="iso8859-1"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:ns1="http://www.w3.org/2001/XMLSchema-instance" ns1:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
  <metadata name="datacollection_period_from">2008-08-17</metadata>
  <metadata name="datacollection_period_to">2008-09-18</metadata>
  <metadata name="bounding_box">179.9058,69.7082,-176.5038,77.1788</metadata>
  <metadata name="variable">sea_water_pressure</metadata>
  <metadata name="variable">ocean chemistry &gt; HIDDEN</metadata>
  <metadata name="variable">sea_water_salinity</metadata>
  <metadata name="area">Arctic Ocean</metadata>
  <metadata name="contact">leifand@chem.gu.se</metadata>
  <metadata name="topiccategory">oceans</metadata>
  <metadata name="PI_name">Leif Anderson</metadata>
  <metadata name="keywords">cruise</metadata>
  <metadata name="keywords">Arctic Ocean</metadata>
  <metadata name="activity_type">Cruise</metadata>
  <metadata name="project_name">ISSS08</metadata>
  <metadata name="Conventions">CF-1.0</metadata>
  <metadata name="Platform_name">R/V Jakov Smirnitskyi</metadata>
  <metadata name="history">created: 2008-12-04 version 1.0</metadata>
  <metadata name="distribution_statement">Restricted to Damocles</metadata>
  <metadata name="abstract">
This data was collected during the International Siberian Shelf Study 2008 
(ISSS08) onboard the Russian research vessel Jakov Smirnitskiy. These data have 
been through a preliminary QC and questionable data have been removed. 
   </metadata>
  <metadata name="title">Carbon sample data from ISSS08 in the Arctic Ocean</metadata>
  <metadata name="institution">UGOT Göteborg University Department of Oceanography - Earth Sciences Centre</metadata>
  <metadata name="product_name">ISSS08 carbon data</metadata>
  <metadata name="dataref">http://damocles.met.no:8080/thredds/catalog/data/UGOT/UGOT-data/</metadata>
</MM2>

=== metno/metamod/test/xmlinput/pops/pops_300124010704000-val.xml
<?xml version="1.0" encoding="utf-8"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
<metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_temperature</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">number_of_profile_samples</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">depth</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_water_salinity</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="area">Arctic Ocean</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="contact">sacha.fouchard@ipev.fr</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="topiccategory">oceans</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="PI_name">Sacha Fouchard</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="keywords">Sea Water Salinity Temperature Depth Ocean </metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="datacollection_period_from">2007-04-26</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="activity_type">Ice station</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="project_name">Damocles</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="Conventions">CF-1.0</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="Platform_name">300124010704000</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="history">2009-02-24 creation</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="distribution_statement">Restricted to Damocles</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="datacollection_period_to">2008-02-13</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="abstract">CTD value packet from POPS 300124010704000 </metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="title">POPS 300124010704000 Values</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="bounding_box">-12.1008,76.085281,133.334702,87.260399</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="institution">IPEV Institut Polaire Fran√ßais - Paul Emile Victor</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="product_name">CTD dataset</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="dataref">http://damocles.met.no:8080/thredds/catalog/data/met.no/pops/catalog.html?dataset=met.no/pops/pops_300124010704000-val.nc</metadata></MM2>

=== metno/metamod/test/xmlinput/UPMC_1.xml
<?xml version="1.0" encoding="iso8859-1"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:ns1="http://www.w3.org/2001/XMLSchema-instance" ns1:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
  <metadata name="datacollection_period_from">2007-09-15</metadata>
  <metadata name="datacollection_period_to">2008-08-15</metadata>
  <metadata name="institution">UPMC Université Pierre et Marie Curie</metadata>
  <metadata name="contact">jga@lodyc.jussieu.fr</metadata>
  <metadata name="dataref">UPMC-1 (planned activity)</metadata>
  <metadata name="activity_type">Float</metadata>
  <metadata name="variable">Cryosphere &gt; Sea Ice &gt; Ice Depth/Thickness &gt; HIDDEN</metadata>
  <metadata name="variable">Oceans &gt; Ocean Circulation &gt; Ocean Currents &gt; HIDDEN</metadata>
  <metadata name="variable">Spectral Engineering &gt; Infrared Wavelengths &gt; Brightness Temperature &gt; HIDDEN</metadata>
  <metadata name="area">Central Arctic</metadata>
  <metadata name="abstract">
Isobaric floats equipped with ULS for measuring sea-ice drafts
Profiling floats for measuring CTD between
surface and 1000m depth.
   </metadata>
</MM2>

=== metno/metamod/test/xmlinput/gmmicemov/gmmicemov_20060821-20060824.xml
<?xml version="1.0" encoding="utf-8"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
<metadata xmlns="http://www.met.no/schema/metamod/MM2" name="area">Arctic Ocean</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="contact">rs@space.dtu.dk</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="topiccategory">oceans</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="PI_name">Roberto Saldo</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="keywords">Ice</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="activity_type">Space borne instrument</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="project_name">DAMOCLES</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="Conventions">CF-1.0</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="history">2006-08-24 creation</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="distribution_statement">Free</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="abstract">Envisat ASAR GMM derived 3 day ice movement </metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="title">GMM ice movement</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="product_name">GMM icemovement</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="dataref">http://damocles.met.no:8080/thredds/catalog/data/DTU/gmmicemov/catalog.html?dataset=DTU/gmmicemov/gmmicemov_20060821-20060824.nc</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="institution">DTU Technical University of Denmark</metadata></MM2>

=== metno/metamod/test/xmlinput/ark22-2-met.xml
<?xml version="1.0" encoding="iso8859-1"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
<metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">global_radiation</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">relative_humidity</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">cloud_base_altitude</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">visibility_in_air</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">air_pressure</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">wind_from_direction</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">dew_point_temperature</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">air_temperature</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">wind_speed</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="area">Arctic Ocean</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="contact">christof.luepkes@awi.de</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="topiccategory">climatologyMeteorologyAtmosphere</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="PI_name">Christof Lüpkes</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="product_version">1.0</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="keywords">arctic soundings</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="keywords">arctic boundary layer</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="references">Damocles deliverables 2.2-05 and 2.3-04 by Lüpkes et al. and http://dship.awi.de/</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="datacollection_period_from">2007-08-01</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="activity_type">Cruise</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="project_name">DAMOCLES</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="Conventions">CF-1.0</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="history">2009-01-22 creation</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="distribution_statement">Restricted to Damocles</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="quality_index">2</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="datacollection_period_to">2007-09-30</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="abstract">meteorological observations from Polarstern cruise ARKXXII/2 to the central 
Arctic Ocean. </metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="title">ark22_2 met_soundings</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="bounding_box">180,78,-180,89</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="institution">AWI Alfred Wegener Institute for Polar and Marine Research</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="product_name">ark22-2-met_polarstern-soundings.nc</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="dataref">http://thredds.met.no/thredds/catalog/data/AWI/ark22-2-met/</metadata></MM2>

=== metno/metamod/catalyst/t/MetamodWeb/Schema/Metabase/ResultSet/datasets/dataset1.xml
<?xml version="1.0" encoding="UTF-8"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
	<metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">lwe_thickness_of_surface_snow_amount</metadata>
	<metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">relative_humidity</metadata>
    <metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">Oceans &gt; Sea Ice &gt; Sea Ice Concentration &gt; HIDDEN</metadata>
	<metadata xmlns="http://www.met.no/schema/metamod/MM2" name="area">Barents Sea</metadata>
	<metadata xmlns="http://www.met.no/schema/metamod/MM2" name="keywords">Test Test2 Test3</metadata>
	<metadata xmlns="http://www.met.no/schema/metamod/MM2" name="datacollection_period_from">2010-01-01</metadata>
    <metadata xmlns="http://www.met.no/schema/metamod/MM2" name="datacollection_period_to">2010-12-31</metadata>
	<metadata xmlns="http://www.met.no/schema/metamod/MM2" name="activity_type">Model run</metadata>
	<metadata xmlns="http://www.met.no/schema/metamod/MM2" name="bounding_box">180,60,-180,90</metadata>
	<metadata xmlns="http://www.met.no/schema/metamod/MM2" name="dataref">http://example.com/thredds//</metadata>
</MM2>

=== metno/metamod/test/xmlinput/iceconc/iceconc_2007-12.xml
<?xml version="1.0" encoding="utf-8"?>
<MM2 xmlns="http://www.met.no/schema/metamod/MM2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.met.no/schema/metamod/MM2 https://wiki.met.no/_media/metamod/mm2.xsd">
<metadata xmlns="http://www.met.no/schema/metamod/MM2" name="variable">sea_ice_area_fraction</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="area">Northern Hemisphere</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="contact">heygster@uni-bremen.de</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="topiccategory">geoscientificinformation</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="topiccategory">oceans</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="PI_name">Georg Heygster</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="product_version">1.0</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="keywords">Space borne instrument</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="references">Spreen, Kaleschke, Heygster, 2008 (doi:10.1029/2005JC003384)</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="datacollection_period_from">2007-12-01</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="activity_type">Space borne instrument</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="project_name">DAMOCLES</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="Conventions">CF-1.0</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="Platform_name">Aqua (NASA)</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="history">2008-01-01 creation</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="distribution_statement">Free</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="quality_index">1</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="software_version">ASI algorithm V.5</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="datacollection_period_to">2007-12-31</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="title">Sea ice concentration derived from AMSR-E</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="abstract">
Sea ice concentration calculated with the ARTIST
Sea Ice (ASI) algorithm (see 
www.seaice.de) using AMSR-E (Advanced
Microwave Scanning Radiometer) data. 
AMSR-E is a multichannel, dual 
polarisation (H and V) radiometer on NASA's 
satellite Aqua.
Ice concentration is the fraction of a satellite footprint 
covered by sea ice, 
given in 0% (no ice) to 100% (totally ice-covered). About 
14 daily
satellite passes; in the Arctic, each point is covered at least 
twice
daily. All satellite passes of one day are interpolated and averaged
onto 
a 6.25 km grid, using the "nearneighbor" routine of the
Generic Mapping Tools 
(GMT) 
 </metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="bounding_box">179.953491210938,31.0110759735107,-180,89.9592056274414</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="institution">UB University of Bremen</metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="product_name">asi-n6250-2008*-v5 </metadata><metadata xmlns="http://www.met.no/schema/metamod/MM2" name="dataref">http://damocles.met.no:8080/thredds/catalog/data/UB/iceconc/catalog.html?dataset=UB/iceconc/iceconc_2007-12.nc</metadata></MM2>
