=== metno/metamod/app/default/etc/conf_digest_nc.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <digest_nc
       xmlns="http://www.met.no/metamod2/conf_digest_nc/"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.met.no/metamod2/conf_digest_nc/ conf_digest_nc.xsd">
    ...
    </digest_nc>

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace='http://www.met.no/metamod2/conf_digest_nc/'
  xmlns='http://www.met.no/metamod2/conf_digest_nc/'
>
  <xs:element name="digest_nc">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="file_structures" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

<xs:element name="file_structures" type='FileStructures' />
<xs:element name="structure"  type='Structure'/>
<xs:element name="variable" type='Variable'/>
<xs:element name="global_attributes" type='GlobalAttributes' />
<xs:element name="attribute_aliases" type='AttributeAliases' />
<xs:element name="investigate_data_dimensions" type='InvestigateDataDimensions'/>
<xs:element name="global" type='Global'/>
<xs:element name="set_global_attribute_value" type='SetGlobalAttributeValue'/>
<xs:element name="variables_of_type" type='VariablesOfType'/>
<xs:element name="set" type='Set'/>
<xs:element name="dim" type='Dim'/>
<xs:element name="att" type='Att' />
<xs:element name="dimensions" type='Dimensions' />
<xs:element name="mandatory" type='Mandatory' />
<xs:element name="vocabulary" type='Vocabulary'/>
<xs:element name="convert" type='Convert'/>
<xs:element name="multivalue" type='MultiValue'/>
<xs:element name="breaklines" type='BreakLines'/>
<xs:element name="aggregate" type='Aggregate'/>

    <xs:complexType name='FileStructures'>
      <xs:sequence>
        <xs:element ref="structure" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name='Structure'>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="variable"/>
        <xs:element ref="global_attributes" />
        <xs:element ref="attribute_aliases" />
        <xs:element ref="investigate_data_dimensions" />
        <xs:element ref="global"/>
        <xs:element ref="set_global_attribute_value"/>
        <xs:element ref="variables_of_type"/>
        <xs:element ref="set"/>
      </xs:choice>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="regex" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:complexType name='Aggregate'>
      <xs:attribute name="rule" type="xs:string" use="required" />
      <xs:attribute name="errmsg" type="xs:string" use="optional" />
    </xs:complexType>


    <xs:complexType name='BreakLines'>
      <xs:attribute name="value" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name='MultiValue'>
      <xs:attribute name="separator" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType mixed="true" name='Convert'>
      <xs:attribute name="dummy" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType mixed="true" name='Vocabulary'>
      <xs:attribute name="on_error" type="xs:string" use="required" />
      <xs:attribute name="escapes" type="xs:string" use="optional" />
      <xs:attribute name="errmsg" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name='Att'>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="vocabulary"/>
        <xs:element ref="convert"/>
        <xs:element ref="multivalue"/>
        <xs:element ref="breaklines"/>
        <xs:element ref="aggregate"/>
        <xs:element ref="mandatory"/>
      </xs:choice>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType mixed="true" name='Dimensions'>
      <xs:attribute name="on_error" type="xs:string" use="optional" />
      <xs:attribute name="escapes" type="xs:string" use="optional" />
      <xs:attribute name="errmsg" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:complexType name='Mandatory'>
      <xs:attribute name="on_error" type="xs:string" use="required" />
      <xs:attribute name="only_if" type="xs:string" use="optional" />
      <xs:attribute name="errmsg" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name='Variable'>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="att"/>
        <xs:element ref="dimensions"/>
        <xs:element ref="mandatory"/>
      </xs:choice>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="if_in_list" type="xs:string" use="optional" />
      <xs:attribute name="comment" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:complexType name='GlobalAttributes'>
      <xs:sequence>
        <xs:element ref="att" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType mixed="true" name='AttributeAliases'>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="errmsg" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name='Dim'>
      <xs:attribute name="addmatches" type="xs:string" use="optional" />
      <xs:attribute name="extendtype" type="xs:string" use="required" />
      <xs:attribute name="rex" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name='InvestigateDataDimensions'>
      <xs:sequence>
        <xs:element ref="dim" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name='Global'>
      <xs:attribute name="lists" type="xs:string" use="optional" />
      <xs:attribute name="switches" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:complexType mixed="true" name='SetGlobalAttributeValue'>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType mixed="true" name='VariablesOfType'>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name='Set'>
      <xs:attribute name="switch" type="xs:string" use="required" />
    </xs:complexType>

</xs:schema>

=== metno/metamod/app/damocles/etc/conf_digest_nc.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<digest_nc
    xmlns="http://www.met.no/metamod2/conf_digest_nc/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.met.no/metamod2/conf_digest_nc/ conf_digest_nc.xsd">
   <file_structures>
      <structure name="MSM0204CTD" regex="/MSM0204CTD[^/]*$">
         <set switch="%IS_INSITU" />
         <variables_of_type name="%Data">
            /^CTD.*$/
         </variables_of_type>
         <set_global_attribute_value name="institution">
            AWI Alfred Wegener Institute for Polar and Marine Research
         </set_global_attribute_value>
      </structure>
      <structure name="icedrift" regex="/icedriftC[^/]*$">
         <set switch="%IS_INSITU" />
         <set_global_attribute_value name="gcmd_keywords">
            Cryosphere > Sea Ice > Sea Ice Motion
            Oceans > Sea Ice > Sea Ice Motion
         </set_global_attribute_value>
         <variables_of_type name="%Data_latitude">
            latitude_reference
         </variables_of_type>
         <variables_of_type name="%Data_longitude">
            longitude_reference
         </variables_of_type>
      </structure>
      <structure name="gmmicemov" regex="/gmmicemov[^/]*$">
         <set switch="%IS_INSITU" />
         <set_global_attribute_value name="institution">
            DTU Technical University of Denmark
         </set_global_attribute_value>
         <set_global_attribute_value name="gcmd_keywords">
            Cryosphere > Sea Ice > Sea Ice Motion
            Oceans > Sea Ice > Sea Ice Motion
         </set_global_attribute_value>
         <variables_of_type name="%Data_latitude">
            latitudefrom
         </variables_of_type>
         <variables_of_type name="%Data_longitude">
            longitudefrom
         </variables_of_type>
      </structure>
      <structure name="default">
         <global switches="%IS_GRIDDED %IS_INSITU" />
         <global lists="%VERTICAL %CASE %LEGALVARNAME" />
         <variables_of_type name="%Coordinate">
            latitude
            longitude
         </variables_of_type>
         <investigate_data_dimensions>
            <dim rex="^time,([^,]+),latitude,longitude$" addmatches="%VERTICAL" extendtype="_latlon" />
            <dim rex="^time,([^,]+),Yc,Xc$" addmatches="%VERTICAL" extendtype="_ycxc" />
            <dim rex="^time,latitude,longitude$" extendtype="_latlon" />
            <dim rex="^time,Yc,Xc$" extendtype="_ycxc" />
            <dim rex="^time$" extendtype="_time" />
            <dim rex="^([^,]+),time$" addmatches="%CASE" extendtype="_casetime" />
            <dim rex="^time,([^,]+)$" addmatches="%VERTICAL" extendtype="_timevertical" />
            <dim rex="^([^,]+)$" addmatches="%CASE" extendtype="_case" />
         </investigate_data_dimensions>
         <attribute_aliases name="institution" errmsg="not_standard_attribute_name">
             Institution
             INSTITUTION
         </attribute_aliases>
         <attribute_aliases name="title" errmsg="not_standard_attribute_name">
             Title
             TITLE
         </attribute_aliases>
         <attribute_aliases name="abstract" errmsg="not_standard_attribute_name">
             Abstract
             ABSTRACT
         </attribute_aliases>
         <attribute_aliases name="topiccategory" errmsg="not_standard_attribute_name">
             Topiccategory
             TopicCategory
             topicCategory
             TOPICCATEGORY
         </attribute_aliases>
         <attribute_aliases name="keywords" errmsg="not_standard_attribute_name">
             Keywords
             KEYWORDS
             keyword
             Keyword
             KEYWORD
         </attribute_aliases>
         <attribute_aliases name="gcmd_keywords" errmsg="not_standard_attribute_name">
             Gcmd_keywords
             GCMD_keywords
             GCMD_KEYWORDS
             gcmd_keyword
             Gcmd_keyword
             GCMD_keyword
             GCMD_KEYWORD
         </attribute_aliases>
         <attribute_aliases name="activity_type" errmsg="not_standard_attribute_name">
             Activity_type
             ACTIVITY_TYPE
         </attribute_aliases>
         <attribute_aliases name="product_name" errmsg="not_standard_attribute_name">
             Product_name
             PRODUCT_NAME
         </attribute_aliases>
         <attribute_aliases name="area" errmsg="not_standard_attribute_name">
             Area
             AREA
         </attribute_aliases>
         <attribute_aliases name="southernmost_latitude" errmsg="not_standard_attribute_name">
             Southernmost_latitude
             SOUTHERNMOST_LATITUDE
         </attribute_aliases>
         <attribute_aliases name="northernmost_latitude" errmsg="not_standard_attribute_name">
             Northernmost_latitude
             NORTHERNMOST_LATITUDE
         </attribute_aliases>
         <attribute_aliases name="westernmost_longitude" errmsg="not_standard_attribute_name">
             Westernmost_longitude
             WESTERNMOST_LONGITUDE
         </attribute_aliases>
         <attribute_aliases name="easternmost_longitude" errmsg="not_standard_attribute_name">
             Easternmost_longitude
             EASTERNMOST_LONGITUDE
         </attribute_aliases>
         <attribute_aliases name="start_date" errmsg="not_standard_attribute_name">
             Start_date
             START_DATE
         </attribute_aliases>
         <attribute_aliases name="stop_date" errmsg="not_standard_attribute_name">
             Stop_date
             STOP_DATE
         </attribute_aliases>
         <attribute_aliases name="PI_name" errmsg="not_standard_attribute_name">
             pi_name
             Pi_name
             PI_NAME
         </attribute_aliases>
         <attribute_aliases name="contact" errmsg="not_standard_attribute_name">
             Contact
             CONTACT
         </attribute_aliases>
         <attribute_aliases name="distribution_statement" errmsg="not_standard_attribute_name">
             Distribution_statement
             DISTRIBUTION_STATEMENT
         </attribute_aliases>
         <attribute_aliases name="project_name" errmsg="not_standard_attribute_name">
             Project_name
             PROJECT_NAME
         </attribute_aliases>
         <global_attributes>
            <att name="title">
               <mandatory on_error="cry_but_continue" errmsg="missing_global_att" />
               <aggregate rule="all_should_be_equal_IFNOT_take_first" errmsg="globatt_different_values" />
            </att>
            <att name="abstract">
               <mandatory on_error="cry_but_continue" errmsg="missing_global_att" />
               <aggregate rule="all_should_be_equal_IFNOT_take_first" errmsg="globatt_different_values" />
               <breaklines value="80" />
            </att>
            <att name="topiccategory">
               <mandatory on_error="cry_but_continue" errmsg="missing_global_att" />
               <aggregate rule="all_should_be_equal_IFNOT_take_first" errmsg="globatt_different_values" />
               <multivalue separator="\s*,\s*" />
               <convert dummy="dummy">
                  Biota :TO: biota
                  ClimatologyMeteorologyAtmosphere :TO: climatologyMeteorologyAtmosphere
                  Environment :TO: environment
                  Geoscientificinformation :TO: geoscientificinformation
                  ImageryBaseMapsEarthCover :TO: imageryBaseMapsEarthCover
                  InlandWaters :TO: inlandWaters
                  Oceans :TO: oceans
                  Society :TO: society
               </convert>
               <vocabulary on_error="notuse" errmsg="illegal_global_att_val">
                  farming
                  biota
                  boundaries
                  climatologyMeteorologyAtmosphere
                  economy
                  elevation
                  environment
                  geoscientficInformation
                  health
                  imageryBaseMapsEarthCover
                  intelligenceMilitary
                  inlandWaters
                  location
                  oceans
                  planningCadastre
                  society
                  structure
                  transportation
                  utilitiesCommunication
               </vocabulary>
            </att>
            <att name="keywords">
               <multivalue separator="\s*,\s*" />
               <mandatory on_error="cry_but_continue" errmsg="missing_global_att" />
               <aggregate rule="take_union" />
            </att>
            <att name="activity_type">
               <multivalue separator="\s*,\s*" />
               <mandatory on_error="cry_but_continue" errmsg="missing_global_att" />
               <aggregate rule="all_should_be_equal_IFNOT_take_first" errmsg="globatt_different_values" />
               <vocabulary on_error="notuse" errmsg="illegal_global_att_val">
                  Moored instrument
                  Cruise
                  Aircraft
                  Model run
                  Land station
                  Ice station
                  Submersible
                  Float
                  Space borne instrument
                  Other
               </vocabulary>
            </att>
            <att name="Conventions">
               <multivalue separator="\s*,\s*" />
               <mandatory on_error="cry_but_continue" errmsg="missing_global_att" />
               <aggregate rule="all_should_be_equal_IFNOT_take_first" errmsg="globatt_different_values" />
               <vocabulary on_error="use" errmsg="illegal_global_att_val">
                  CF-1.0
                  CF-1.1
                  CF-1.2
               </vocabulary>
            </att>
            <att name="product_name">
               <mandatory on_error="cry_but_continue" errmsg="missing_global_att" />
